### ISSUE TITLE
Attach virtual folder with alias name

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-webui#1081]
**Is your feature request related to a problem? Please describe.**

Virtual folder aliasing is not currently implemented in the GUI. Let's implement aliasing function in node.js SDK and UI so that user can mount a virtual folder by renaming it when mounting.

**Describe the solution you'd like**

Attach virtual folder with alias name

<img width="397" alt="image" src="https://user-images.githubusercontent.com/949915/126481104-f263887c-68be-457a-bdaa-924e9b53c027.png">

 * [x] Implement node.js SDK
 * [x] Add UI for folder name aliases

**Describe alternatives you've considered**

**Additional context**

**Comment by lizable** [comment]
@inureyes I guess the basic feature of aliasing virtual folder has been resolved via #1082.
Btw, @SonMinWoo is working on implelementing feature for aliasing not just for directory name but also on arbitrary path that written by user. (Issue: [backend.ai#329](https://github.com/lablup/backend.ai/issues/329) PR: #1194)
If this issue is related, I'll add a related comment, but if not, I think we should close this issue.
