### ISSUE TITLE
Inconsistent width of environment dropdown menu in the session launch dialog

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai-webui#1084]
When I opened the "Environment" dropdown menu in the session launch dialog, the width of the list of items is wider than the mother element if there is a vertical scrollbar.

**How to reproduce**
* Open a session launch dialog.
* Click "Environment".
  - The list of environments should be long enough to display the vertical scrollbar.
* The width of the item container is wider than that of the dropdown field.

**Expected behavior**
Consistent width of the environment list element.

**Screenshots**
<img width="476" alt="image" src="https://user-images.githubusercontent.com/7539358/126991398-c53db7d0-b340-4eb3-a248-97f59fd3f0b9.png">

**Client:**
 - OS: macOS 11.4
 - Browser version: Chrome 91.0.4472.114

**Comment by Damdinbazar** [comment]
There are a few things to consider:

1. It could have been resolved easily with `overflow: overlay`, which lets the scrollbar appear on top of the content rather than pushing the content. however, it is deprecated.
2. Another option would be using the `scrollbar-gutter: stable`, but `#experimental-web-platform-features` flag has to be enabled in `chrome://flags` 
3. I could not reproduce this in Safari, so it can be browser-specific.

I think one of the solutions is setting the mwc-list width fixed considering the scrollbar width.

Other suggestions needed.

**Comment by Damdinbazar** [comment]
It's not reproducible anymore as the scrollbar appears on top of the contents.
