### ISSUE TITLE
Refactor Pipeline feature

### ISSUE THREAD

**Issue by adrysn** [lablup/backend.ai-webui#1169]
We have implemented a pipeline page/feature last year, but it has not been touched for the last year, so the page is not loaded properly. Let's refactor the pipeline feature to display the page normally.

* Remove the `display:none` style from the line to appear the "Pipeline" sidebar menu.
  - https://github.com/lablup/backend.ai-webui/blob/44a8b8a35d99278cf41c1dffa90fd017f28994b5/src/components/backend-ai-webui.ts#L1293
* Click the "Pipeline" menu on the left sidebar to access the page. The page should be broken.
* Fix the broken sources (`src/components/backend.ai-pipeline-*`) to display the page.
* This issue focuses only on the visual display of the pipeline page and its components. The actual runtime feature should be implemented separately after the graph batch session template is implemented from the backend.

**Comment by lizable** [comment]
We need to split the current pipeline page (which is a single page, for now) into two, one is for "pipeline template", and the other is for "pipeline" itself since the pipeline is instantiated from the pipeline template.

**Comment by lizable** [comment]
### ⚠️ NOTE! Major Changes
In order to keep the modularity of [Backend.AI project](https://github.com/backend.ai) and the dependency of each component, we decided to refactor Pipeline to independent directory and components.

There are two big changes in the current structure.
1. Pipeline page will be split into **two pages**.
   - pipeline-template
   - pipeline-runner
2. Every component that contains the pipeline page will be handled in `src/pipeline` to make it easier to separate from current component.
> The hierarchy of pipeline components:
>  `src/pipeline`
>  - lib
>      - pipeline-list
>      - pipeline-dialog
>      - pipeline-flow (We will use [DrawFlow](https://github.com/jerosoler/Drawflow))
>  - component
>      - pipeline-template-view
>      - pipeline-template-list
>      - pipeline-runner-view
>      - pipeline-runner-list

There's also a hierarchy provided for UI components on each page. Please refer to the image below.
![Component Hierarchy ver 1](https://user-images.githubusercontent.com/46954439/152505934-971ba0eb-fd2d-40b6-bc31-6104ca5edf0f.svg)



According to the description above, we need two steps to achieve.

Step 1. Build base component for Pipeline pages.
- [ ] a. Build pipeline-list
- [ ] b. Build pipeline-dialog
- [ ] c. Build pipeline-flow

Step 2. Build pipeline pages with components implemented in Step 1.
- [ ] a. Build pipeline-template-view
- [ ] b. Build pipeline-template-list
- [ ] c. Build pipeline-runner-view
- [ ] d. Build pipeline-runner-list

**Comment by lizable** [comment]
@Sujin-Kim1 will be in charge of implementing a,b in step 1 and c,d in step 2.
I'll be in charge of implementing c in step 1 and a, b in step 2.

**Comment by lizable** [comment]
Step 3. Validation check on user's input.
- [ ] a. pipeline creation/update
- [ ] b. task creation/update

**Comment by lizable** [comment]
## Updates

### Hierarchy changes
In order to provide better code readability and easier for maintaining each component related to pipeline feature,
I updated components by splitting some parts and adding a custom-defined type component, `pipeline-configuration-form`, and `pipeline-type` as an example.
Here's the hierarchy that has been updated in the latest commits.
![Pipeline Template UI Flow - Component Hierarchy ver 2](https://user-images.githubusercontent.com/46954439/183562539-a2c11a39-7784-4e5f-b74c-ddef67e503ed.png)
