### ISSUE TITLE
Show warning dialog when setting rate limit below 100

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-webui#1469]
### Main idea

The rate limit function limits the number of API calls per 900 seconds to prevent unexpected DDoS attacks and API abuse. However, if this value is too small, API operations such as login using API calls will also be blocked. 

The rate limit value is also used to block spammers, so the setting can be as small as 1 as before, but when setting a value less than 100, let's improve the user interface to provide a warning and a dialog asking to continue.

**Comment by Sujin-Kim1** [comment]
When the rate limit value is lower than the warning threshold, I am debating whether to display the validity as false or change the color of the helpertext.
Since it is a settable value, validity cannot be considered false, but it has the advantage of being able to see a warning message immediately along with the user's input.
On the other hand, helpertext has the disadvantage that it cannot be reflected immediately along with the user's input, but it is theoretically appropriate. (valid)

**Comment by lizable** [comment]
FWIW, I think we could use "lablup-slider" rather than plain text field in order to describe what the amount of the value means. Perhaps like this?
![1_HSdwlQS2XBgAaUUNu_Mf4A](https://user-images.githubusercontent.com/46954439/190341098-74b88ece-d5ff-4cb2-b90c-003e9c706404.gif)
(ref: https://uxplanet.org/4-creative-concepts-of-slider-control-1f8839b05943)

**Comment by lizable** [comment]
To apply those UI, we need to separate the issue into two.
- [ ] Refactor lablup-slider or Create another slider component that supports color-adjustable option by range.
- [ ] Apply "custom slider" to rate limit section.

**Comment by inureyes** [comment]
Let's add option to Lablup-slider!
