### ISSUE TITLE
bug: Rescanning image progress doesn't work properly

### ISSUE THREAD

**Issue by yomybaby** [lablup/backend.ai-webui#1943]
reported by @lizable  on [Teams](https://teams.microsoft.com/l/message/19:3c0acc0825024daeb2211f55c4e7f4aa@thread.skype/1695626352073?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=74ae2c4d-ec4d-4fdf-b2c2-f5041d1e8631&parentMessageId=1695626352073&teamName=devops&channelName=Backend.AI%20Talks&createdTime=1695626352073):
> I found it during removing the image in agent-side (all-in-one, though), and the progress bar stay still even if the manager log is printing out
"Updates - <image-name>"
after requesting rescanning image command and printing out
bgtask done.

![Image](https://github.com/lablup/backend.ai-webui/assets/621215/70dc2b03-54a7-4621-b360-fa2578b003f2)

**Comment by lizable** [comment]
Closing this issue, because this issus is as well-known as CORS(Cross-Origin-Resource-Sharing) issue.
By suggestion of @yomybaby , I tried changing [IP address of the configuration of the webserver in Backend.AI Monorepo](https://github.com/lablup/backend.ai/blob/9a733556c348a3f8f673d0becb6e73d3ab2b3872/configs/webserver/sample.conf#L2) as the same IP address that webUI server has and the problem has been solved without any code manipulation.
