### ISSUE TITLE
The size changes when the '확인' button in the start model serving modal is clicked.

### ISSUE THREAD

**Issue by Yaminyam** [lablup/backend.ai-webui#2113]
### What Operating System(s) are you seeing this problem on?

Linux (x86-64)

### Backend.AI version

main

### Describe the bug

![CleanShot 2023-12-20 at 18 14 39](https://github.com/lablup/backend.ai-webui/assets/31057849/b10a2e4e-da9d-4794-af8a-75504c2d50e4)

**Comment by ironAiken2** [comment]
This issue was that the loading indicator, which shows the request time on the button, becomes significantly shorter when the request fails.

could solve the issue by artificially extending the loading time, but since we are already displaying a message regarding that logic, so closed the issue without any further modifications.
