### ISSUE TITLE
Dropdown in allowed host at resource policies modification dialog breaks the layout when it is expanded

### ISSUE THREAD

**Issue by inureyes** [lablup/backend.ai-webui#785]
**Describe the bug**

Dropdown in allowed host at resource policies modification dialog breaks the layout when it is expanded.

**To Reproduce**
문제를 재현하기 위한 순서를 자세히 적어주세요:
1. Go to 'resource policy' on 'users' menu
2. Click on gear icon
3. Click allowed hosts

**Expected behavior**
원래 기대했던 동작은 어떤 것인지 명확하게 적어주세요.

**Screenshots**
Just take a screenshot in your clipboard or copy a picture file and paste it here (Ctrl+V/Cmd+V) so that GitHub automatically attach and insert it.
가능하다면, 문제 상황을 보여주는 스크린샷을 첨부해주세요.
클립보드에 스크린샷을 찍거나 이미지 파일을 복사해서 여기에 붙여넣으면(Ctrl+V/Cmd+V) GitHub이 자동으로 이곳에 첨부 및 삽입해줍니다.

**Client:**
 - OS: macOS 11.0
 - App version: 20.11.0 (if you are using a GUI client app)
 - Browser version: Firefox 83 (if you are using a GUI web console)

**Additional context**

<img width="306" alt="image" src="https://user-images.githubusercontent.com/949915/99221501-08698980-2824-11eb-87a2-d8dc414ffb89.png">

**Comment by lizable** [comment]
I presume that this issue was solved by adding temporary spaces when the dropdown is opened.
When it comes to manipulating the natural direction of the dropdown element,
even if the purpose of It is simply to avoid overlapping elements, It might confuse in maintaining the code.
Therefore If this bug is enough to be handled by adding some spaces, then I guess this issue could be closed now.
